{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[nltk_data] Downloading package punkt to\n",
      "[nltk_data]     C:\\Users\\DELL\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package punkt is already up-to-date!\n",
      "[nltk_data] Downloading package wordnet to\n",
      "[nltk_data]     C:\\Users\\DELL\\AppData\\Roaming\\nltk_data...\n",
      "[nltk_data]   Package wordnet is already up-to-date!\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "152 documents\n",
      "39 classes ['Age_group', 'Cloud_features', 'Experiences', 'Impact', 'Inner_explorer', 'Language', 'Mindfulness', 'Mindfulness_Programs', 'Mobile_app', 'Name', 'Need_mindfulness', 'Trial_audio', 'Well_being', 'advicefor_child', 'all_cost', 'app_availability', 'appreciation', 'audio_language', 'bad', 'chatbot', 'cloud_cost', 'community_cost', 'district_cost', 'download_app', 'goodbye', 'greeting', 'no_access_student', 'noanswer', 'parent', 'practice-detail', 'program_advice', 'school district', 'schools', 'single_school', 'smart', 'steps', 'support', 'thanks', 'work']\n",
      "199 unique lemmatized words [\"'m\", \"'s\", \"'ve\", ',', '.', '1', '13', '2', '3', 'a', 'achievement', 'actually', 'additional', 'advantage', 'age-group', 'agenda', 'aggressive', 'all', 'am', 'amazing', 'an', 'and', 'answer', 'any', 'anyone', 'app', 'are', 'at', 'audio', 'availability', 'available', 'average', 'awesome', 'be', 'best', 'brief', 'but', 'bye', 'can', 'chatting', 'child', 'choose', 'clear', 'cloud', 'community', 'concept', 'confused', 'cost', 'could', 'day', 'disappointed', 'district', 'distrubed/stressed', 'do', 'doe', 'doubt', 'download', 'each', 'effect', 'effective', 'experience', 'explain', 'explorer', 'feature', 'fee', 'few', 'find', 'foolish', 'for', 'from', 'generally', 'get', 'good', 'goodbye', 'great', 'guide', 'he', 'hello', 'help', 'helpful', 'helping', 'hey', 'hi', 'him', 'hola', 'home', 'how', 'i', 'identity', 'idiot', 'ie', 'impact', 'in', 'inner', 'inner_explorer', 'is', 'isssue', 'it', 'know', 'language', 'later', 'leading', 'level', 'like', 'little', 'lockdown', 'login', 'many', 'me', 'meditation', 'mindfulness', 'mobile', 'much', 'my', 'name', 'need', 'next', 'nice', 'no', 'now', 'number', 'of', 'offer', 'offered', 'old', 'out', 'over', 'parent', 'people', 'plan', 'play', 'please', 'practice', 'practicing', 'program', 'provide', 'remains', 'resolve', 'result', 'review', 'running', 'school', 'see', 'share', 'should', 'show', 'sign', 'single', 'smart', 'some', 'something', 'start', 'structure', 'student', 'stupid', 'such', 'suit', 'suitable', 'support', 'tell', 'term', 'thank', 'thanks', 'thanku', 'thankyou', 'that', 'the', 'there', 'this', 'till', 'time', 'to', 'too', 'total', 'trial', 'u', 'unable', 'understand', 'up', 'ur', 'use', 'useful', 'useless', 'user', 'very', 'wat', 'we', 'well', 'what', 'where', 'which', 'who', 'why', 'will', 'work', 'would', 'year', 'you', 'your']\n",
      "Training data created\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\DELL\\AppData\\Roaming\\Python\\Python36\\site-packages\\ipykernel_launcher.py:86: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.6249 - accuracy: 0.0243 \n",
      "Epoch 2/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.5872 - accuracy: 0.0769\n",
      "Epoch 3/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.5570 - accuracy: 0.0771\n",
      "Epoch 4/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.3250 - accuracy: 0.1453\n",
      "Epoch 5/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.4807 - accuracy: 0.0638\n",
      "Epoch 6/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.1548 - accuracy: 0.1603\n",
      "Epoch 7/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 3.0036 - accuracy: 0.2262\n",
      "Epoch 8/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.8551 - accuracy: 0.2711\n",
      "Epoch 9/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.7684 - accuracy: 0.3021\n",
      "Epoch 10/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.4941 - accuracy: 0.2965\n",
      "Epoch 11/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.4787 - accuracy: 0.3143\n",
      "Epoch 12/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.2298 - accuracy: 0.4120\n",
      "Epoch 13/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 2.0729 - accuracy: 0.4186\n",
      "Epoch 14/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.9278 - accuracy: 0.4309\n",
      "Epoch 15/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.8438 - accuracy: 0.5236\n",
      "Epoch 16/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.7719 - accuracy: 0.4841\n",
      "Epoch 17/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.4895 - accuracy: 0.5346\n",
      "Epoch 18/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.7489 - accuracy: 0.5297\n",
      "Epoch 19/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.5371 - accuracy: 0.5629\n",
      "Epoch 20/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.3327 - accuracy: 0.5605\n",
      "Epoch 21/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.2304 - accuracy: 0.7043\n",
      "Epoch 22/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.4931 - accuracy: 0.5634\n",
      "Epoch 23/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.2762 - accuracy: 0.6254\n",
      "Epoch 24/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.1604 - accuracy: 0.6300\n",
      "Epoch 25/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.3613 - accuracy: 0.6004\n",
      "Epoch 26/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.9166 - accuracy: 0.6889\n",
      "Epoch 27/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 1.1040 - accuracy: 0.6989\n",
      "Epoch 28/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.8789 - accuracy: 0.7388\n",
      "Epoch 29/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.9374 - accuracy: 0.7732\n",
      "Epoch 30/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.9693 - accuracy: 0.6796\n",
      "Epoch 31/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.9651 - accuracy: 0.7147\n",
      "Epoch 32/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.8072 - accuracy: 0.7667\n",
      "Epoch 33/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.7534 - accuracy: 0.8148\n",
      "Epoch 34/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.8068 - accuracy: 0.7706\n",
      "Epoch 35/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.8388 - accuracy: 0.7208\n",
      "Epoch 36/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.6410 - accuracy: 0.8104\n",
      "Epoch 37/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.9017 - accuracy: 0.7623\n",
      "Epoch 38/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.7858 - accuracy: 0.7756\n",
      "Epoch 39/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.7364 - accuracy: 0.7321\n",
      "Epoch 40/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.6474 - accuracy: 0.8008\n",
      "Epoch 41/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.7185 - accuracy: 0.7684\n",
      "Epoch 42/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5791 - accuracy: 0.8167\n",
      "Epoch 43/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.8013 - accuracy: 0.8184\n",
      "Epoch 44/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.6082 - accuracy: 0.8054\n",
      "Epoch 45/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5513 - accuracy: 0.8368\n",
      "Epoch 46/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.6865 - accuracy: 0.7651\n",
      "Epoch 47/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5744 - accuracy: 0.8422\n",
      "Epoch 48/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5153 - accuracy: 0.8221\n",
      "Epoch 49/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5197 - accuracy: 0.8259\n",
      "Epoch 50/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4497 - accuracy: 0.8363\n",
      "Epoch 51/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3792 - accuracy: 0.9081\n",
      "Epoch 52/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3474 - accuracy: 0.9331\n",
      "Epoch 53/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5537 - accuracy: 0.8381\n",
      "Epoch 54/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4849 - accuracy: 0.8697\n",
      "Epoch 55/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5211 - accuracy: 0.8364\n",
      "Epoch 56/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3523 - accuracy: 0.9143\n",
      "Epoch 57/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4481 - accuracy: 0.8683\n",
      "Epoch 58/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5172 - accuracy: 0.8237\n",
      "Epoch 59/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4710 - accuracy: 0.8490\n",
      "Epoch 60/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5319 - accuracy: 0.8183\n",
      "Epoch 61/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4069 - accuracy: 0.8793\n",
      "Epoch 62/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4536 - accuracy: 0.8274\n",
      "Epoch 63/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3760 - accuracy: 0.8951\n",
      "Epoch 64/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4174 - accuracy: 0.8491\n",
      "Epoch 65/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3266 - accuracy: 0.9220\n",
      "Epoch 66/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3620 - accuracy: 0.9048\n",
      "Epoch 67/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3576 - accuracy: 0.8869\n",
      "Epoch 68/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4133 - accuracy: 0.8320\n",
      "Epoch 69/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3068 - accuracy: 0.9203\n",
      "Epoch 70/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3925 - accuracy: 0.8892\n",
      "Epoch 71/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.5233 - accuracy: 0.8437\n",
      "Epoch 72/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3731 - accuracy: 0.9021\n",
      "Epoch 73/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3660 - accuracy: 0.8912\n",
      "Epoch 74/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4225 - accuracy: 0.8973\n",
      "Epoch 75/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3830 - accuracy: 0.8969\n",
      "Epoch 76/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3604 - accuracy: 0.8842\n",
      "Epoch 77/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2024 - accuracy: 0.9550\n",
      "Epoch 78/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3053 - accuracy: 0.9053\n",
      "Epoch 79/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3087 - accuracy: 0.8931\n",
      "Epoch 80/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2727 - accuracy: 0.9184\n",
      "Epoch 81/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3920 - accuracy: 0.9036\n",
      "Epoch 82/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2790 - accuracy: 0.8895\n",
      "Epoch 83/200\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2987 - accuracy: 0.9242\n",
      "Epoch 84/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2257 - accuracy: 0.9317\n",
      "Epoch 85/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1960 - accuracy: 0.9167\n",
      "Epoch 86/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2880 - accuracy: 0.9085\n",
      "Epoch 87/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2665 - accuracy: 0.9395\n",
      "Epoch 88/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4204 - accuracy: 0.9066\n",
      "Epoch 89/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8833\n",
      "Epoch 90/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2963 - accuracy: 0.8651\n",
      "Epoch 91/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2893 - accuracy: 0.8863\n",
      "Epoch 92/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2234 - accuracy: 0.9558\n",
      "Epoch 93/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2219 - accuracy: 0.9368\n",
      "Epoch 94/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2141 - accuracy: 0.9406\n",
      "Epoch 95/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3647 - accuracy: 0.8676\n",
      "Epoch 96/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2443 - accuracy: 0.9483\n",
      "Epoch 97/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2858 - accuracy: 0.8818\n",
      "Epoch 98/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2458 - accuracy: 0.9052\n",
      "Epoch 99/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2462 - accuracy: 0.9098\n",
      "Epoch 100/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2446 - accuracy: 0.9280\n",
      "Epoch 101/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2672 - accuracy: 0.9050\n",
      "Epoch 102/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2708 - accuracy: 0.9175\n",
      "Epoch 103/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3270 - accuracy: 0.8647\n",
      "Epoch 104/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3036 - accuracy: 0.9057\n",
      "Epoch 105/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2298 - accuracy: 0.9279\n",
      "Epoch 106/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2412 - accuracy: 0.9587\n",
      "Epoch 107/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1951 - accuracy: 0.9517\n",
      "Epoch 108/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4618 - accuracy: 0.8743\n",
      "Epoch 109/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2281 - accuracy: 0.9152\n",
      "Epoch 110/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1923 - accuracy: 0.9363\n",
      "Epoch 111/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2942 - accuracy: 0.8980\n",
      "Epoch 112/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2780 - accuracy: 0.9037\n",
      "Epoch 113/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2369 - accuracy: 0.9122\n",
      "Epoch 114/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1980 - accuracy: 0.9601\n",
      "Epoch 115/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2839 - accuracy: 0.9124\n",
      "Epoch 116/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3128 - accuracy: 0.8703\n",
      "Epoch 117/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3075 - accuracy: 0.8891\n",
      "Epoch 118/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2706 - accuracy: 0.9055\n",
      "Epoch 119/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3673 - accuracy: 0.9196\n",
      "Epoch 120/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2237 - accuracy: 0.9050\n",
      "Epoch 121/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.4484 - accuracy: 0.8655\n",
      "Epoch 122/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2514 - accuracy: 0.9309\n",
      "Epoch 123/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1666 - accuracy: 0.9551\n",
      "Epoch 124/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2995 - accuracy: 0.9099\n",
      "Epoch 125/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2771 - accuracy: 0.9202\n",
      "Epoch 126/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1164 - accuracy: 0.9809\n",
      "Epoch 127/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2809 - accuracy: 0.9110\n",
      "Epoch 128/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1968 - accuracy: 0.9402\n",
      "Epoch 129/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2000 - accuracy: 0.9276\n",
      "Epoch 130/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2472 - accuracy: 0.9087\n",
      "Epoch 131/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2633 - accuracy: 0.9079\n",
      "Epoch 132/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1583 - accuracy: 0.9318\n",
      "Epoch 133/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1618 - accuracy: 0.9544\n",
      "Epoch 134/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1690 - accuracy: 0.9487\n",
      "Epoch 135/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1655 - accuracy: 0.9696\n",
      "Epoch 136/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2026 - accuracy: 0.9775\n",
      "Epoch 137/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1903 - accuracy: 0.9364\n",
      "Epoch 138/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2422 - accuracy: 0.9098\n",
      "Epoch 139/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2699 - accuracy: 0.8868\n",
      "Epoch 140/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2984 - accuracy: 0.8915\n",
      "Epoch 141/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2100 - accuracy: 0.9360\n",
      "Epoch 142/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2770 - accuracy: 0.9178\n",
      "Epoch 143/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2803 - accuracy: 0.9027\n",
      "Epoch 144/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2975 - accuracy: 0.8923\n",
      "Epoch 145/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2694 - accuracy: 0.9174\n",
      "Epoch 146/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2269 - accuracy: 0.9380\n",
      "Epoch 147/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1274 - accuracy: 0.9421\n",
      "Epoch 148/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1145 - accuracy: 0.9767\n",
      "Epoch 149/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2100 - accuracy: 0.9285\n",
      "Epoch 150/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1744 - accuracy: 0.9195\n",
      "Epoch 151/200\n",
      "31/31 [==============================] - 0s 2ms/step - loss: 0.1638 - accuracy: 0.9414\n",
      "Epoch 152/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1502 - accuracy: 0.9645\n",
      "Epoch 153/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1962 - accuracy: 0.9322\n",
      "Epoch 154/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1241 - accuracy: 0.9599\n",
      "Epoch 155/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1636 - accuracy: 0.9523\n",
      "Epoch 156/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2120 - accuracy: 0.8997\n",
      "Epoch 157/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1672 - accuracy: 0.9479\n",
      "Epoch 158/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2431 - accuracy: 0.9164\n",
      "Epoch 159/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2840 - accuracy: 0.8934\n",
      "Epoch 160/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2268 - accuracy: 0.9634\n",
      "Epoch 161/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.0613 - accuracy: 0.9759\n",
      "Epoch 162/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2493 - accuracy: 0.8976\n",
      "Epoch 163/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1349 - accuracy: 0.9473\n",
      "Epoch 164/200\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1842 - accuracy: 0.9491\n",
      "Epoch 165/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1394 - accuracy: 0.9493\n",
      "Epoch 166/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2571 - accuracy: 0.9219\n",
      "Epoch 167/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1658 - accuracy: 0.9344\n",
      "Epoch 168/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1236 - accuracy: 0.9569\n",
      "Epoch 169/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.0978 - accuracy: 0.9751\n",
      "Epoch 170/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1215 - accuracy: 0.9516\n",
      "Epoch 171/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2060 - accuracy: 0.9632\n",
      "Epoch 172/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1128 - accuracy: 0.9788\n",
      "Epoch 173/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1050 - accuracy: 0.9724\n",
      "Epoch 174/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.0822 - accuracy: 0.9716\n",
      "Epoch 175/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2718 - accuracy: 0.9076\n",
      "Epoch 176/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.3693 - accuracy: 0.8630\n",
      "Epoch 177/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1375 - accuracy: 0.9781\n",
      "Epoch 178/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1611 - accuracy: 0.9453\n",
      "Epoch 179/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1199 - accuracy: 0.9653\n",
      "Epoch 180/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2126 - accuracy: 0.9411\n",
      "Epoch 181/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1584 - accuracy: 0.9511\n",
      "Epoch 182/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2661 - accuracy: 0.9320\n",
      "Epoch 183/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2000 - accuracy: 0.9182\n",
      "Epoch 184/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1813 - accuracy: 0.9161\n",
      "Epoch 185/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2013 - accuracy: 0.9358\n",
      "Epoch 186/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1387 - accuracy: 0.9387\n",
      "Epoch 187/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1589 - accuracy: 0.9551\n",
      "Epoch 188/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.0916 - accuracy: 0.9746\n",
      "Epoch 189/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1271 - accuracy: 0.9644\n",
      "Epoch 190/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2385 - accuracy: 0.9298\n",
      "Epoch 191/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1247 - accuracy: 0.9548\n",
      "Epoch 192/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1286 - accuracy: 0.9654\n",
      "Epoch 193/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1984 - accuracy: 0.9491\n",
      "Epoch 194/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1744 - accuracy: 0.9527\n",
      "Epoch 195/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2965 - accuracy: 0.9496\n",
      "Epoch 196/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.0811 - accuracy: 0.9765\n",
      "Epoch 197/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1572 - accuracy: 0.9786\n",
      "Epoch 198/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.2938 - accuracy: 0.9245\n",
      "Epoch 199/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1455 - accuracy: 0.9438\n",
      "Epoch 200/200\n",
      "31/31 [==============================] - 0s 1ms/step - loss: 0.1588 - accuracy: 0.9507\n",
      "model created\n"
     ]
    }
   ],
   "source": [
    "#Chatbot Training Model\n",
    "import os\n",
    "import pyttsx3\n",
    "import time\n",
    "import playsound\n",
    "import speech_recognition as sr\n",
    "from gtts import gTTS\n",
    "from spellchecker import SpellChecker\n",
    "from textblob import TextBlob\n",
    "import emoji\n",
    "import time\n",
    "import nltk\n",
    "nltk.download('punkt')\n",
    "nltk.download('wordnet')\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "lemmatizer = WordNetLemmatizer()\n",
    "import json\n",
    "import pickle\n",
    "\n",
    "import numpy as np\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense, Activation, Dropout\n",
    "from keras.optimizers import SGD\n",
    "import random\n",
    "\n",
    "words=[]\n",
    "classes = []\n",
    "documents = []\n",
    "ignore_words = ['?', '!']\n",
    "data_file = open('cap_intents.json',encoding=\"utf8\").read()\n",
    "intents = json.loads(data_file)\n",
    "\n",
    "\n",
    "for intent in intents['intents']:\n",
    "    for pattern in intent['patterns']:\n",
    "\n",
    "        #tokenize each word\n",
    "        w = nltk.word_tokenize(pattern)\n",
    "        words.extend(w)\n",
    "        #add documents in the corpus\n",
    "        documents.append((w, intent['tag']))\n",
    "\n",
    "        # add to our classes list\n",
    "        if intent['tag'] not in classes:\n",
    "            classes.append(intent['tag'])\n",
    "\n",
    "# lemmaztize and lower each word and remove duplicates\n",
    "words = [lemmatizer.lemmatize(w.lower()) for w in words if w not in ignore_words]\n",
    "words = sorted(list(set(words)))\n",
    "# sort classes\n",
    "classes = sorted(list(set(classes)))\n",
    "# documents = combination between patterns and intents\n",
    "print (len(documents), \"documents\")\n",
    "# classes = intents\n",
    "print (len(classes), \"classes\", classes)\n",
    "# words = all words, vocabulary\n",
    "print (len(words), \"unique lemmatized words\", words)\n",
    "\n",
    "\n",
    "pickle.dump(words,open('words.pkl','wb'))\n",
    "pickle.dump(classes,open('classes.pkl','wb'))\n",
    "\n",
    "# create our training data\n",
    "training = []\n",
    "# create an empty array for our output\n",
    "output_empty = [0] * len(classes)\n",
    "# training set, bag of words for each sentence\n",
    "for doc in documents:\n",
    "    # initialize our bag of words\n",
    "    bag = []\n",
    "    # list of tokenized words for the pattern\n",
    "    pattern_words = doc[0]\n",
    "    # lemmatize each word - create base word, in attempt to represent related words\n",
    "    pattern_words = [lemmatizer.lemmatize(word.lower()) for word in pattern_words]\n",
    "    # create our bag of words array with 1, if word match found in current pattern\n",
    "    for w in words:\n",
    "        bag.append(1) if w in pattern_words else bag.append(0)\n",
    "    \n",
    "    # output is a '0' for each tag and '1' for current tag (for each pattern)\n",
    "    output_row = list(output_empty)\n",
    "    output_row[classes.index(doc[1])] = 1\n",
    "    \n",
    "    training.append([bag, output_row])\n",
    "# shuffle our features and turn into np.array\n",
    "random.shuffle(training)\n",
    "training = np.array(training)\n",
    "# create train and test lists. X - patterns, Y - intents\n",
    "train_x = list(training[:,0])\n",
    "train_y = list(training[:,1])\n",
    "print(\"Training data created\")\n",
    "\n",
    "\n",
    "# Create model - 3 layers. First layer 128 neurons, second layer 64 neurons and 3rd output layer contains number of neurons\n",
    "# equal to number of intents to predict output intent with softmax\n",
    "model = Sequential()\n",
    "model.add(Dense(128, input_shape=(len(train_x[0]),), activation='relu'))\n",
    "model.add(Dropout(0.5))\n",
    "model.add(Dense(64, activation='relu'))\n",
    "model.add(Dropout(0.5))\n",
    "model.add(Dense(len(train_y[0]), activation='softmax'))\n",
    "\n",
    "# Compile model. Stochastic gradient descent with Nesterov accelerated gradient gives good results for this model\n",
    "sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)\n",
    "model.compile(loss='categorical_crossentropy', optimizer=sgd, metrics=['accuracy'])\n",
    "\n",
    "#fitting and saving the model \n",
    "hist = model.fit(np.array(train_x), np.array(train_y), epochs=200, batch_size=5, verbose=1)\n",
    "model.save('chatbot_model.h5', hist)\n",
    "\n",
    "print(\"model created\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Chatbot API\n",
    "\n",
    "from spellchecker import SpellChecker\n",
    "import random\n",
    "import multiprocessing\n",
    "from flask import Flask,json, render_template, request\n",
    "from flask_cors import CORS\n",
    "import time\n",
    "import nltk\n",
    "from multiprocessing import Process\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "lemmatizer = WordNetLemmatizer()\n",
    "import pickle\n",
    "import json\n",
    "import numpy as np\n",
    "from keras.models import load_model\n",
    "model = load_model('chatbot_model.h5')\n",
    "intents = json.loads(open('cap_intents.json',encoding=\"utf8\").read())\n",
    "words = pickle.load(open('words.pkl','rb'))\n",
    "classes = pickle.load(open('classes.pkl','rb'))\n",
    "app= Flask(__name__)\n",
    "CORS(app)\n",
    "# @app.route('/run/<msg>') \n",
    "def chatbot(msg):\n",
    "    msg=SpellChecker().correction(msg)\n",
    "    \n",
    "    def clean_up_sentence(sentence):\n",
    "        # token,aize the pattern - split words into array\n",
    "        sentence_words = nltk.word_tokenize(sentence)\n",
    "        # stem each word - create short form for word\n",
    "        sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]\n",
    "        return sentence_words\n",
    "    # return bag of words array: 0 or 1 for each word in the bag that exists in the sentence\n",
    "    def bow(sentence, words, show_details=True):\n",
    "        # tokenize the pattern\n",
    "        sentence_words = clean_up_sentence(sentence)\n",
    "        # bag of words - matrix of N words, vocabulary matrix\n",
    "        bag = [0]*len(words)  \n",
    "        for s in sentence_words:\n",
    "            for i,w in enumerate(words):\n",
    "                if w == s: \n",
    "                    # assign 1 if current word is in the vocabulary position\n",
    "                    bag[i] = 1\n",
    "                    if show_details:\n",
    "                        print (\"found in bag: %s\" % w)\n",
    "        return(np.array(bag))\n",
    "    def predict_class(sentence, model):\n",
    "        # filter out predictions below a threshold\n",
    "        p = bow(sentence, words,show_details=False)\n",
    "        \n",
    "        res = model.predict(np.array([p]))[0]\n",
    "        ERROR_THRESHOLD = 0.25\n",
    "        results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]\n",
    "        # sort by strength of probability\n",
    "        results.sort(key=lambda x: x[1], reverse=True)\n",
    "        return_list = []\n",
    "        for r in results:\n",
    "            return_list.append({\"intent\": classes[r[0]], \"probability\": str(r[1])})\n",
    "        return return_list \n",
    "    def getResponse(ints, intents_json):\n",
    "        tag = ints[0]['intent']\n",
    "        list_of_intents = intents_json['intents']\n",
    "        for i in list_of_intents:\n",
    "            if(i['tag']== tag):\n",
    "                result = random.choice(i['responses'])\n",
    "                #result1 = random.choice(i['responses1'])\n",
    "                break\n",
    "        return result\n",
    "    def chatbot_response(text):\n",
    "        ints = predict_class(text, model)\n",
    "        res = getResponse(ints, intents)\n",
    "        return res\n",
    "    \n",
    "    def send():\n",
    "        print(msg,\"input\")\n",
    "        while True:#it used to be in continunation and to stop it press alt+cntrl+c\n",
    "            #msg=input(\"You:- \")\n",
    "            \n",
    "            if msg==\"quit\":\n",
    "                break\n",
    "            else:\n",
    "                res=chatbot_response(msg)\n",
    "                \n",
    "                return {\"Bot\":[res]}\n",
    "    return send()\n",
    "#     if __name__ == '__main__':\n",
    "    p = Process(target=chatbot)\n",
    "    p.start()\n",
    "    p.join()\n",
    "# if __name__== \"__main__\":\n",
    "#     app.run(host='172.31.52.129',port=5000)\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "stupid input\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "{'Bot': ['Sometimes I make mistakes😞, but I can learn from them.\\nCan you ask question again?']}"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "chatbot(\"stupid?\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "from spellchecker import SpellChecker\n",
    "import random\n",
    "import multiprocessing\n",
    "from flask import Flask,json, render_template, request\n",
    "from flask_cors import CORS\n",
    "import time\n",
    "import nltk\n",
    "from multiprocessing import Process\n",
    "from nltk.stem import WordNetLemmatizer\n",
    "from tensorflow.python.keras.backend import reset_uids\n",
    "lemmatizer = WordNetLemmatizer()\n",
    "import pickle\n",
    "import json\n",
    "import datetime\n",
    "import numpy as np\n",
    "import os\n",
    "import pyttsx3\n",
    "import time\n",
    "import playsound\n",
    "import speech_recognition as sr\n",
    "from gtts import gTTS\n",
    "from keras.models import load_model\n",
    "model = load_model('chatbot_model.h5')\n",
    "intents = json.loads(open('cap_intents.json',encoding=\"utf8\").read())\n",
    "words = pickle.load(open('words.pkl','rb'))\n",
    "classes = pickle.load(open('classes.pkl','rb'))\n",
    "currentTime = datetime.datetime.now()\n",
    "currentTime.hour\n",
    "app= Flask(__name__)\n",
    "CORS(app)\n",
    "# @app.route('/run') \n",
    "def greeting():\n",
    "    if currentTime.hour < 12:\n",
    "        return {\"Bot\": ['Hi,Good Morning! Genie at service.']}\n",
    "    elif 12 <= currentTime.hour < 18:\n",
    "        return {\"Bot\": ['Hi,Good Afternoon! Genie at service.']}\n",
    "    else:\n",
    "        return {\"Bot\": ['Hi,Good evening! Genie at service.']}\n",
    "@app.route('/run/<msg>') \n",
    "def chatbot(msg):\n",
    "    msg=SpellChecker().correction(msg)\n",
    "    \n",
    "    def clean_up_sentence(sentence):\n",
    "        # token,aize the pattern - split words into array\n",
    "        sentence_words = nltk.word_tokenize(sentence)\n",
    "        # stem each word - create short form for word\n",
    "        sentence_words = [lemmatizer.lemmatize(word.lower()) for word in sentence_words]\n",
    "        return sentence_words\n",
    "    # return bag of words array: 0 or 1 for each word in the bag that exists in the sentence\n",
    "    def bow(sentence, words, show_details=True):\n",
    "        # tokenize the pattern\n",
    "        sentence_words = clean_up_sentence(sentence)\n",
    "        # bag of words - matrix of N words, vocabulary matrix\n",
    "        bag = [0]*len(words)  \n",
    "        for s in sentence_words:\n",
    "            for i,w in enumerate(words):\n",
    "                if w == s: \n",
    "                    # assign 1 if current word is in the vocabulary position\n",
    "                    bag[i] = 1\n",
    "                    if show_details:\n",
    "                        print (\"found in bag: %s\" % w)\n",
    "        return(np.array(bag))\n",
    "    def predict_class(sentence, model):\n",
    "        # filter out predictions below a threshold\n",
    "        p = bow(sentence, words,show_details=False)\n",
    "        \n",
    "        res = model.predict(np.array([p]))[0]\n",
    "        ERROR_THRESHOLD = 0.25\n",
    "        results = [[i,r] for i,r in enumerate(res) if r>ERROR_THRESHOLD]\n",
    "        # sort by strength of probability\n",
    "        results.sort(key=lambda x: x[1], reverse=True)\n",
    "        return_list = []\n",
    "        for r in results:\n",
    "            return_list.append({\"intent\": classes[r[0]], \"probability\": str(r[1])})\n",
    "        return return_list \n",
    "        print(return_list )\n",
    "    \n",
    "    def getResponse(ints, intents_json):\n",
    "        tag = ints[0]['intent']\n",
    "        list_of_intents = intents_json['intents']\n",
    "        for i in list_of_intents:\n",
    "            if(i['tag']== tag):\n",
    "                result = random.choice(i['responses'])\n",
    "                #result1 = random.choice(i['responses1'])\n",
    "                break\n",
    "        return result\n",
    "        \n",
    "    \n",
    "    def chatbot_response(text):\n",
    "        ints = predict_class(text, model)\n",
    "        res = getResponse(ints, intents)\n",
    "        return res\n",
    "    \n",
    "    \n",
    "#     engine = pyttsx3.init('nsss')\n",
    "    engine=pyttsx3.init('sapi5')\n",
    "    voices=engine.getProperty('voices')\n",
    "    voice_id = \"com.apple.speech.synthesis.voice.samantha\"\n",
    "#     engine.setProperty('voice',voice_id)\n",
    "    engine.setProperty('voice','voices[0].id')\n",
    "    def speak(text):\n",
    "        engine.say(text)\n",
    "        engine.runAndWait()\n",
    "    def get_audio():\n",
    "        r = sr.Recognizer()\n",
    "        with sr.Microphone() as source:\n",
    "            audio = r.listen(source)\n",
    "            said = \"\"\n",
    "            try:\n",
    "                said = r.recognize_google(audio)\n",
    "                print(said)\n",
    "            except Exception as e:\n",
    "                print(\"Exception: \" + str(e))\n",
    "        return said\n",
    "    def send():\n",
    "        print(msg,\"input\")\n",
    "        while True:#it used to be in continunation and to stop it press alt+cntrl+c\n",
    "            #msg=input(\"You:- \")\n",
    "            \n",
    "            if msg==\"quit\":\n",
    "                break\n",
    "            else:\n",
    "                res=chatbot_response(msg)\n",
    "                prob=predict_class(msg, model)\n",
    "            \n",
    "                \n",
    "                return {\"Bot\":[res],\"probability\":[prob]}, speak(res)\n",
    "                \n",
    "                \n",
    "                # return {\"Bot\":[res]}\n",
    "    return send()\n",
    "    \n",
    "        \n",
    "    if __name__ == '__main__':\n",
    "        p = Process(target=chatbot)\n",
    "        p.start()\n",
    "        p.join()\n",
    "# if __name__== \"__main__\":\n",
    "#     app.run(threaded=False,port=5000)\n",
    "    # app.run(host='172.31.52.129',port=5000)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "hello input\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "({'Bot': [\"Hi there! I'm GENIE. How Can I help you?😊\"],\n",
       "  'probability': [[{'intent': 'greeting', 'probability': '0.9997259'}]]},\n",
       " None)"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "chatbot(\"hello\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "yourenvname",
   "language": "python",
   "name": "yourenvname"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
